# Generated by Django 3.2.8 on 2021-12-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('datetime_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed')])),
                ('comments', models.CharField(max_length=50)),
                ('datetime_audited', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('depreciation_rate', models.FloatField(default=0.01)),
                ('memo', models.CharField(max_length=50)),
                ('image_file', models.FileField(null=True, upload_to='uploads/')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('audit_status', models.ManyToManyField(through='api.Audit', to='api.AuditStatus')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditstatus'),
        ),
        migrations.AddField(
            model_name='audit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
